{"Image Source": ["images/profile-photo/abdullahsalman.jpg"], "Name": ["Abdullah Salman"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/abdullahasalman"], "Study Program": "FullStack Web Developer"}
{"Image Source": ["images/profile-photo/abdulqadir.jpg"], "Name": ["Abdul Qadir"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/aqadir1"], "Study Program": "FullStack Web Developer"}
{"Image Source": ["images/profile-photo/alinatariq.jpg"], "Name": ["Alina Tariq"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/dr-alina-zeshan-50a886124/"], "Study Program": "Data Analyst"}
{"Image Source": ["images/profile-photo/aliraza.jpg"], "Name": ["Ali Raza"], "Status": "In Progress", "linkedIn Profile": ["https://pk.linkedin.com/in/brainlet\r\n"], "Study Program": "Android Developer"}
{"Image Source": ["images/profile-photo/alisaleem.jpg"], "Name": ["Ali Saleem"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/ali-saleem-79563998/\r\n"], "Study Program": "Android Developer"}
{"Image Source": ["images/profile-photo/amanullah.jpg"], "Name": ["Aman Ullah"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/aman-ullah-743b0a76/"], "Study Program": "Intro To Programming"}
{"Image Source": ["images/profile-photo/ammarakhalid.jpg"], "Name": ["Ammara Khalid"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/ammara-khalid-9a1389157"], "Study Program": "Android Developer"}
{"Image Source": ["images/profile-photo/ayeshanaveed.jpg"], "Name": ["Ayesha Naveed"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/ayesha-naved\r\n"], "Study Program": "FullStack Web Developer"}
{"Image Source": ["images/profile-photo/farhanbakht.jpg"], "Name": ["Farhan Bakht"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/muhammad-farhan-bakht-a2021b163/\r\n"], "Study Program": "Android Developer"}
{"Image Source": ["images/profile-photo/faridmushtaq.jpg"], "Name": ["Farid Mushtaq"], "Status": "Withdrawn", "linkedIn Profile": ["https://www.linkedin.com/in/farid-mushtaq-980979b9/\r\n"], "Study Program": "Android Developer"}
{"Image Source": ["images/profile-photo/hasnanyaqoob.jpg"], "Name": ["Hasnan Yaqoob"], "Status": "In Progress", "linkedIn Profile": ["javascript:void(0);"], "Study Program": "FullStack Web Developer"}
{"Image Source": ["images/profile-photo/hassanabbasi.jpg"], "Name": ["Hassan Abbasi"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/muhammad-hassan-abbasi-b17760130/\r\n"], "Study Program": "Front-End Web Developer"}
{"Image Source": ["images/profile-photo/hassanali.jpg"], "Name": ["Hassan Ali"], "Status": "In Progress", "linkedIn Profile": ["javascript:void(0);"], "Study Program": "FullStack Web Developer"}
{"Image Source": ["images/profile-photo/ibtesamuddin.jpg"], "Name": ["Ibtesam Uddin"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/ibtesam-uddin-365b8b101/"], "Study Program": "Front-End Web Developer"}
{"Image Source": ["images/profile-photo/ishtiaqhussain.jpg"], "Name": ["Ishtiaq Hussain"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/ishtiaq-hussain-79944b160/"], "Study Program": "Front-End Web Developer"}
{"Image Source": ["images/profile-photo/kamrantariq.jpg"], "Name": ["Kamran Tariq"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/kamrankami555/"], "Study Program": "Data Analyst"}
{"Image Source": ["images/profile-photo/kashifiqbal.jpg"], "Name": ["Kashif Iqbal"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/kashif1994"], "Study Program": "FullStack Web Developer"}
{"Image Source": ["images/profile-photo/mansoorbilal.jpg"], "Name": ["Mansoor Bilal"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/mansoorbilal/\r\n"], "Study Program": "FullStack Web Developer"}
{"Image Source": ["images/profile-photo/mubasharali.jpg"], "Name": ["Mubashar Ali"], "Status": "Withdrawn", "linkedIn Profile": ["javascript:void(0);"], "Study Program": "Front-End Web Developer"}
{"Image Source": ["images/profile-photo/muhammadzubair.jpg"], "Name": ["Muhammad Zubair"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/muhammad-zubair-shakoor-733216a2"], "Study Program": "FullStack Web Developer"}
{"Image Source": ["images/profile-photo/mujtabaahmad.jpg"], "Name": ["Mujtaba Ahmad"], "Status": "Withdrawn", "linkedIn Profile": ["https://www.linkedin.com/in/mujtaba-ahmad-0239b9bb/"], "Study Program": "Front-End Web Developer"}
{"Image Source": ["images/female-placeholder.gif"], "Name": ["Nimra Arshad"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/mujtaba-ahmad-0239b9bb/"], "Study Program": "Intro To Programming"}
{"Image Source": ["images/profile-photo/quratulainfatima.jpg"], "Name": ["Qurat Ul Ain Fatima"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/qurat-ul-ain-fatima/\r\n"], "Study Program": "Front-End Web Developer"}
{"Image Source": ["images/profile-photo/ramshasaeed.jpg"], "Name": ["Ramsha Saeed"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/ramsha-saeed\r\n"], "Study Program": "Android Developer"}
{"Image Source": ["images/profile-photo/razaakmal.jpg"], "Name": ["Raza Akmal"], "Status": "Withdrawn", "linkedIn Profile": ["https://www.linkedin.com/in/raza-akmal-15b615121/\r\n"], "Study Program": "Android Developer"}
{"Image Source": ["images/profile-photo/razawahga.jpg"], "Name": ["Raza Wahga"], "Status": "In Progress", "linkedIn Profile": ["javascript:void(0);"], "Study Program": "Android Developer"}
{"Image Source": ["images/profile-photo/shahabuddin.jpg"], "Name": ["Shahabuddin"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/shahabee/\r\n"], "Study Program": "Intro To Programming"}
{"Image Source": ["images/profile-photo/shaheryarkhan.jpg"], "Name": ["Shaheryar Khan"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/muhammad-shaheryar-shakaib-khan-5a6ab6114\r\n"], "Study Program": "Data Analyst"}
{"Image Source": ["images/profile-photo/sohailkhan.jpg"], "Name": ["Sohail Khan"], "Status": "Withdrawn", "linkedIn Profile": ["https://www.linkedin.com/in/sohail-khan-6a921680/\r\n"], "Study Program": "Android Developer"}
{"Image Source": ["images/profile-photo/sufyanhanif.jpg"], "Name": ["Sufyan Hanif"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/muhammad-sufyan-haneef-671082144/"], "Study Program": "Android Developer"}
{"Image Source": ["images/profile-photo/syedhasan.jpg"], "Name": ["Syed Hasan"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/syed-hasan97"], "Study Program": "Android Developer"}
{"Image Source": ["images/profile-photo/umerbaig.jpg"], "Name": ["Umer Baig"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/umerahmedbaig/\r\n"], "Study Program": "React JS"}
{"Image Source": ["images/profile-photo/yasirrazakhan.jpg"], "Name": ["Yasir Raza Khan"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/yasirrazakhan/"], "Study Program": "FullStack Web Developer"}
{"Image Source": ["images/profile-photo/zaimabutt.jpg"], "Name": ["Zaima Butt"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/zaima-butt-93a9a9121\r\n"], "Study Program": "Front-End Web Developer"}
{"Image Source": ["images/profile-photo/zeeshankhan.jpg"], "Name": ["Zeeshan Khan"], "Status": "Withdrawn", "linkedIn Profile": ["https://www.linkedin.com/in/zeeshan-anwar-khan-192302154/\r\n"], "Study Program": "Android Developer"}
{"Image Source": ["images/profile-photo/rahoon-nizami.jpg"], "Name": ["Rahoon Nizami"], "Status": "Completed", "linkedIn Profile": ["https://www.linkedin.com/in/rahoon-ahmed-nizami-63730a120/"], "Study Program": "Intro to Programming"}
{"Image Source": ["images/profile-photo/kashan-osama.jpg"], "Name": ["Kashan Osama Tahir"], "Status": "In Progress", "linkedIn Profile": ["https://pk.linkedin.com/in/kashanosama"], "Study Program": "Data Analyst"}
{"Image Source": ["images/profile-photo/vanesh-kumar.jpg"], "Name": ["Vanesh Kumar"], "Status": "Withdrawn", "linkedIn Profile": ["https://www.linkedin.com/in/vanesh-kumar-maheshwari/"], "Study Program": "Data Analyst"}
{"Image Source": ["images/profile-photo/syed-hassan.jpg"], "Name": ["Syed Hassan"], "Status": "In Progress", "linkedIn Profile": ["https://www.linkedin.com/in/syed-hasan97/ "], "Study Program": "Android Developer"}
